"use client";

import { useQuery } from "@tanstack/react-query";
import { fetchSignals } from "@/utils/api";
import SignalCard from "./SignalCard";
import { motion, AnimatePresence } from "framer-motion";
import { RefreshCcw, AlertCircle } from "lucide-react";

export default function SignalFeed() {
  const { data: signals, isLoading, isError, refetch, isRefetching } = useQuery({
    queryKey: ["signals"],
    queryFn: fetchSignals,
    refetchInterval: 10000, // Refresh every 10 seconds
  });

  if (isLoading) {
    return (
      <div className="flex flex-col items-center justify-center py-20">
        <RefreshCcw className="w-8 h-8 text-cyan-500 animate-spin mb-4" />
        <p className="text-white/40 font-mono text-xs uppercase tracking-widest">Synchronizing Alpha Stream...</p>
      </div>
    );
  }

  if (isError) {
    return (
      <div className="p-8 bg-red-500/5 border border-red-500/20 rounded-2xl flex flex-col items-center text-center">
        <AlertCircle className="w-12 h-12 text-red-500 mb-4" />
        <h3 className="text-xl font-bold text-white mb-2">Alpha Stream Interrupted</h3>
        <p className="text-white/40 text-sm max-w-md mb-6">
          Unable to establish connection with the Signal Engine. Ensure the backend services are operational.
        </p>
        <button 
          onClick={() => refetch()}
          className="px-6 py-2 bg-red-500 text-white rounded-xl font-bold text-xs uppercase tracking-widest hover:bg-red-600 transition-colors"
        >
          Retry Connection
        </button>
      </div>
    );
  }

  const activeSignals = signals?.filter((s: any) => s.direction !== "NO_TRADE") || [];

  return (
    <div className="w-full">
      <div className="flex justify-between items-center mb-8">
        <div>
          <h2 className="text-2xl font-bold text-white mb-1">Signal Stream</h2>
          <p className="text-white/40 text-sm">Real-time trading opportunities generated by Alpha Factory.</p>
        </div>
        <div className="flex items-center gap-4">
          {isRefetching && (
             <div className="flex items-center gap-2 text-[10px] text-cyan-400 font-mono uppercase tracking-widest">
               <RefreshCcw className="w-3 h-3 animate-spin" />
               Updating
             </div>
          )}
          <div className="px-3 py-1 bg-white/5 border border-white/5 rounded-full text-[10px] text-white/60 font-mono">
            COUNT: {activeSignals.length}
          </div>
        </div>
      </div>

      {activeSignals.length === 0 ? (
        <div className="py-20 text-center border-2 border-dashed border-white/5 rounded-3xl">
          <p className="text-white/20 font-mono uppercase tracking-tighter text-lg">No active signals found in current market state</p>
          <p className="text-white/10 text-xs mt-2">The system is monitoring markets for high-probability setups.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
          <AnimatePresence mode="popLayout">
            {activeSignals.map((signal: any) => (
              <SignalCard key={signal.id || signal.timestamp} signal={signal} />
            ))}
          </AnimatePresence>
        </div>
      )}
    </div>
  );
}
